config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main_app.views import (contacts, ProductDetailView, ProductsListView, PostListView,
                            PostDetailView, PostCreateView, PostDeleteView, PostUpdateView,
                            ProductCreateView, ProductDeleteView, ProductUpdateView, VersionDetailView,
                            VersionCreateView, VersionUpdateView)

app_name = 'main_app'

urlpatterns = [
    path('', cache_page(60)(ProductsListView.as_view()), name='product-list'),
    path('contacts/', contacts, name='contacts'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product-detail'),
    path('product/form/', ProductCreateView.as_view(), name='product-form'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product-delete'),
    path('product/edit/<int:pk>/', ProductUpdateView.as_view(), name='product-edit'),

    path('posts/', cache_page(60)(PostListView.as_view()), name='post-list'),
    path('post/<int:pk>/', cache_page(60)(PostDetailView.as_view()), name='post-detail'),
    path('post/form/', PostCreateView.as_view(), name='post-form'),
    path('post/delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('post/edit/<int:pk>/', PostUpdateView.as_view(), name='post-edit'),

    path('version/<int:version_id>/', cache_page(60)(VersionDetailView.as_view()), name='version-detail'),
    path('version/form/', VersionCreateView.as_view(), name='version-form'),
    path('version/edit/<int:pk>/', VersionUpdateView.as_view(), name='version-edit'),
]

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path, include

from users.views import (RegisterView, ProfileView, ConfirmRegister, CustomLogoutView, UserPasswordResetView,
                         UserPasswordResetDoneView, UserPasswordResetConfirmView, UserPasswordResetCompleteView, )

app_name = 'users'
urlpatterns = [
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/confirm/', ConfirmRegister.as_view(), name='confirm_register'),
]

main_app/models.py
from django.db import models
from django.db.models import ForeignKey

from users.models import User


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='название')
    description = models.TextField(verbose_name='описание')
    image = models.ImageField(upload_to='products/', verbose_name='изображение', null=True, blank=True)
    category = models.CharField(max_length=100, verbose_name='категория')
    price_per_unit = models.IntegerField(verbose_name='цена за единицу')
    creation_date = models.DateField(auto_now_add=True, verbose_name='дата создания')
    last_modified_date = models.DateField(auto_now=True, verbose_name='дата последнего изменения')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner', null=True, blank=True)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name} {self.category} {self.price_per_unit}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('name', )

        permissions = [
            ("cancel_product_publication", "Отмена публикации продукта"),
            ("change_product_description", "Изменение описания продукта"),
            ("change_product_category", "Изменение категории продукта"),
        ]


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='название')
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name', )


class Post(models.Model):
    title = models.CharField(max_length=500, verbose_name='название')
    slug = models.TextField(verbose_name='slug')
    content = models.TextField(verbose_name='контент')
    image = models.ImageField(upload_to='blog/', verbose_name='изображение', null=True, blank=True)
    creation_date = models.DateField(verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='статус публикации', null=True, blank=True)
    views_count = models.IntegerField(verbose_name='кол-во просмотров', null=True, blank=True)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'сообщение блога'
        verbose_name_plural = 'сообщения блога'
        ordering = ('title', )


class ProductVersion(models.Model):
    version_name = models.CharField(max_length=200, verbose_name='version name')
    version_number = models.CharField(max_length=100, verbose_name='version number', default='1.0.0')
    is_active = models.BooleanField(default=True, verbose_name='статус версии', null=True, blank=True)
    product = ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True, verbose_name='product')

    class Meta:
        verbose_name = 'Версия продукта'
        verbose_name_plural = 'Версии продукта'
        ordering = ('version_number', )

main_app/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django import forms

from main_app.models import Product, Category, Post, ProductVersion


class ProductCreateForm(ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(),
                                      widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Product
        fields = ('name', 'description', 'image', 'category', 'price_per_unit')

    def clean_name(self):
        name = self.cleaned_data['name']
        forbidden_words = ["казино", "криптовалюта", "крипто", "биржа", "дешево", "бесплатно",
                           "мошенничество", "полиция", "радар"]

        for word in forbidden_words:
            if word.lower() in name.lower():
                raise ValidationError(f"Слово '{word}' запрещено использовать в названии продукта. ")

        return name

    def clean_description(self):
        description = self.cleaned_data['description']
        forbidden_words = ["казино", "криптовалюта", "крипто", "биржа", "дешево", "бесплатно",
                           "мошенничество", "полиция", "радар"]

        for word in forbidden_words:
            if word.lower() in description.lower():
                raise ValidationError(f"Слово '{word}' запрещено использовать в описании продукта.")

        return description


class ProductUpdateForm(ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(),
                                      widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Product
        fields = ('name', 'description', 'image', 'category', 'price_per_unit')


class PostCreateForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'image')


class PostUpdateForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'image')


class VersionCreateForm(ModelForm):
    class Meta:
        model = ProductVersion
        fields = ('version_name', 'version_number', )


class VersionUpdateForm(ModelForm):
    class Meta:
        model = ProductVersion
        fields = ('version_name', 'version_number', )

main_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.utils.text import slugify
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from main_app.forms import (ProductCreateForm, ProductUpdateForm, PostCreateForm, PostUpdateForm, VersionCreateForm,
                            VersionUpdateForm)
from main_app.models import Product, Post, ProductVersion


class ProductsListView(ListView):
    model = Product
    template_name = 'main_app/product/product_list.html'
    context_object_name = 'products'


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'main_app/product/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()

        try:
            version = ProductVersion.objects.get(product=product)
        except ProductVersion.DoesNotExist:
            version = None

        context['version'] = version
        return context


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductCreateForm
    success_url = reverse_lazy('main_app:product-list')
    template_name = 'main_app/product/product_form.html'
    permission_required = 'main_app.add_product'

    def form_valid(self, form):
        form.instance.views_count = 0
        form.instance.user_email = self.request.user.email
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductUpdateForm
    template_name = 'main_app/product/product_form.html'
    permission_required = 'main_app.change_product'

    def get_success_url(self):
        return reverse('main_app:product-detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.last_modified_date = timezone.now()
        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()

        if request.user != self.object.owner:
            return HttpResponseForbidden("Вы не являетесь владельцем продукта. "
                                         "У вас нет прав для его редактирования.")

        return super().dispatch(request, *args, **kwargs)


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = 'main_app/product/product_confirm_delete.html'
    success_url = reverse_lazy('main_app:product-list')
    permission_required = 'main_app.delete_product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Удаление поста'
        return context


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        print(f'{name}: {email}')
    return render(request, 'main_app/contacts.html')


class PostDetailView(DetailView):
    model = Post
    template_name = 'main_app/post/post_detail.html'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class PostListView(ListView):
    model = Post
    template_name = 'main_app/post/post_list.html'
    context_object_name = 'posts'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class PostCreateView(CreateView):
    model = Post
    form_class = PostCreateForm
    success_url = reverse_lazy('main_app:post-list')
    template_name = 'main_app/post/post_form.html'

    def form_valid(self, form):
        form.instance.creation_date = timezone.now()
        form.instance.views_count = 0
        form.instance.slug = slugify(form.instance.title)
        return super().form_valid(form)


class PostUpdateView(UpdateView):
    model = Post
    form_class = PostUpdateForm
    template_name = 'main_app/post/post_form.html'

    def get_success_url(self):
        return reverse('main_app:post-detail', kwargs={'pk': self.object.pk})


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'main_app/post/post_confirm_delete.html'
    success_url = reverse_lazy('main_app:post-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Удаление поста'
        return context


class VersionDetailView(DetailView):
    model = ProductVersion
    template_name = 'main_app/version/version_detail.html'
    context_object_name = 'version'

    def get_object(self, queryset=None):
        version_id = self.kwargs.get('version_id')
        return ProductVersion.objects.get(id=version_id)


class VersionCreateView(CreateView):
    model = ProductVersion
    form_class = VersionCreateForm
    template_name = 'main_app/version/version_form.html'

    def form_valid(self, form):
        product = get_object_or_404(Product, id=self.kwargs.get('pk'))
        form.instance.product = product
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('main_app:product-detail', kwargs={'pk': self.kwargs.get('pk')})


class VersionUpdateView(UpdateView):
    model = ProductVersion
    template_name = 'main_app/version/version_form.html'
    form_class = VersionUpdateForm

    def get_success_url(self):
        return reverse('main_app:version-detail', kwargs={'version_id': self.object.pk})

main_app/templates/main_app/base.html
 <!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<nav class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/posts/">Отзывы покупателей</a>
    </nav> 
    <nav class="ms-md-auto d-flex">
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        {% if user.is_authenticated %}
            {% csrf_token %}
            <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button type="submit" class="p-2 btn btn-outline-primary me-2">Выйти</button>
            </form>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary " href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">
Добро пожаловать в Skystore - ваш персональный портал в мир инноваций и стиля. Мы рады представить вам наш новый
        онлайн магазин, где каждый продукт — это история, а каждая покупка — шаг вперёд к лучшему.</p>
</div>

{% block content %}
{% endblock %}

{% include 'main_app/includes/inc_main_menu.html' %}

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

main_app/templates/main_app/contacts.html
{% extends 'main_app/base.html' %}

{% block title %}Контакты{% endblock %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
   <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Расскажите о ситуации" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}